DEEPSORT:
  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"

  # MAX_DIST: 0.2 # どれくらい似てない人も同idを付与するか
  # MIN_CONFIDENCE: 0.3 # yolovでのconfがこれ以下なら無視
  # NMS_MAX_OVERLAP: 0.5 # 基準画像の比較対象に対してどれだけ重なっているか
  # MAX_IOU_DISTANCE: 0.7
  # MAX_AGE: 70 # cascade depth
  # N_INIT: 3 # マッチング回数がこれ未満だとconfirmedにならない(id飛び現象の原因)
  # NN_BUDGET: 100


  # MAX_DIST: 0.2
  # MIN_CONFIDENCE: 0.3
  # NMS_MAX_OVERLAP: 0.5
  # MAX_IOU_DISTANCE: 0.7
  # MAX_AGE: 70
  # N_INIT: 3
  # NN_BUDGET: 100

  # MAX_DIST: 0.7
  # MIN_CONFIDENCE: 0.3
  # NMS_MAX_OVERLAP: 0.5
  # MAX_IOU_DISTANCE: 0.7
  # MAX_AGE: 200
  # N_INIT: 3
  # NN_BUDGET: 200

  # MAX_DIST: 1.0
  # MIN_CONFIDENCE: 0.3
  # NMS_MAX_OVERLAP: 0.5
  # MAX_IOU_DISTANCE: 0.7
  # MAX_AGE: 200
  # N_INIT: 3
  # NN_BUDGET: 200


  # MAX_DIST: 0.05
  # MIN_CONFIDENCE: 0.3
  # NMS_MAX_OVERLAP: 0.5
  # MAX_IOU_DISTANCE: 0.7
  # MAX_AGE: 200
  # N_INIT: 3
  # NN_BUDGET: 200


  MAX_DIST: 1.5
  MIN_CONFIDENCE: 0.3 
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 1000
  N_INIT: 3
  NN_BUDGET: 200